Traceback (most recent call last):
  File "C:\Users\UPWr\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
z_csv = pd.read_csv('temperatures.txt',nrows = 10,dtype=float)
z_csv
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_25544\2749768939.py[0m in [0;36m<cell line: 0>[1;34m()[0m
[1;32m----> 1[1;33m [0mz_csv[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'temperatures.txt'[0m[1;33m,[0m[0mnrows[0m [1;33m=[0m [1;36m10[0m[1;33m,[0m[0mdtype[0m[1;33m=[0m[0mfloat[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mz_csv[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    209[0m                 [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    210[0m                     [0mkwargs[0m[1;33m[[0m[0mnew_arg_name[0m[1;33m][0m [1;33m=[0m [0mnew_arg_value[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 211[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    212[0m [1;33m[0m[0m
[0;32m    213[0m         [1;32mreturn[0m [0mcast[0m[1;33m([0m[0mF[0m[1;33m,[0m [0mwrapper[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    329[0m                     [0mstacklevel[0m[1;33m=[0m[0mfind_stack_level[0m[1;33m([0m[1;33m)[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    330[0m                 )
[1;32m--> 331[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    332[0m [1;33m[0m[0m
[0;32m    333[0m         [1;31m# error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[0;32m    948[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    949[0m [1;33m[0m[0m
[1;32m--> 950[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    951[0m [1;33m[0m[0m
[0;32m    952[0m [1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    603[0m [1;33m[0m[0m
[0;32m    604[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 605[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    606[0m [1;33m[0m[0m
[0;32m    607[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m   1440[0m [1;33m[0m[0m
[0;32m   1441[0m         [0mself[0m[1;33m.[0m[0mhandles[0m[1;33m:[0m [0mIOHandles[0m [1;33m|[0m [1;32mNone[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1442[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mf[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1443[0m [1;33m[0m[0m
[0;32m   1444[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m [1;33m->[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_make_engine[1;34m(self, f, engine)[0m
[0;32m   1733[0m                 [1;32mif[0m [1;34m"b"[0m [1;32mnot[0m [1;32min[0m [0mmode[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1734[0m                     [0mmode[0m [1;33m+=[0m [1;34m"b"[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1735[1;33m             self.handles = get_handle(
[0m[0;32m   1736[0m                 [0mf[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1737[0m                 [0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\anaconda3\Lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    854[0m         [1;32mif[0m [0mioargs[0m[1;33m.[0m[0mencoding[0m [1;32mand[0m [1;34m"b"[0m [1;32mnot[0m [1;32min[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    855[0m             [1;31m# Encoding[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 856[1;33m             handle = open(
[0m[0;32m    857[0m                 [0mhandle[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    858[0m                 [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'temperatures.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'temperatures.txt'

